name: Build, Test, and Lint
on:
  push:
    branches: [dev**]
    paths-ignore:
      - "**.md"
      - .vscode/**
  pull_request_target:
    types:
      - opened
    branches:
      - main
    paths-ignore:
      - "**.md"
      - .vscode/**

jobs:
  test:
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run lint
        run: pnpm lint
        continue-on-error: true

      - name: Run unit tests
        run: pnpm test